/* tslint:disable */
export const servicoConfig = [
  [
    {
      "nomeCampo": "srvGrupoServicoId",
      "titulo": "Grupo serviço",
      "subtitulo": "Grupo de serviço de referência",
      "valorPadrao": null,
      "editavel": true,
      "obrigatorio": true,
      "visivel": true,
      "tipoDado": null,
      "ordem": 0,
      "isChavePrimaria": false,
      "isChaveEstrangeira": false,
      "nomeColuna": "srvGrupoServicoId",
      "include": null,
      "views": [
        "viewInsert",
        "viewUpdate",
        "viewVisualizacao",
        "viewListagem"
      ],
      "expandOdata": false,
      "selectOdata": false,
      "noFilter": false,
      "conditionSql": false,
      "conditionSqlIfTrue": null,
      "conditionSqlIfFalse": null,
      "filtro": null,
      "componente": {
        "tipo": "comboEdit",
        "recurso": "http://localhost:3000/api/fake/servico/grupo/lista/combo",
        "comboSemChave": true
      },
      "dicionario": null,
      "enumList": false
    },
    {
      "nomeCampo": "codigo",
      "titulo": "Código",
      "subtitulo": "Código do serviço",
      "valorPadrao": null,
      "editavel": true,
      "obrigatorio": false,
      "visivel": true,
      "tipoDado": "texto",
      "ordem": 0,
      "isChavePrimaria": false,
      "isChaveEstrangeira": false,
      "nomeColuna": "codigo",
      "include": null,
      "views": [
        "viewInsert",
        "viewUpdate",
        "viewVisualizacao",
        "viewListagem"
      ],
      "expandOdata": false,
      "selectOdata": false,
      "noFilter": false,
      "conditionSql": false,
      "conditionSqlIfTrue": null,
      "conditionSqlIfFalse": null,
      "filtro": null,
      "componente": {
        "tamanhoMaximo": 20,
        "tamanhoMinimo": 0,
        "formato": "texto",
        "tipo": "textEdit",
        "typeId": "Framework.DataValidations.TextEditAttribute, FrameWork, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
      },
      "dicionario": null,
      "enumList": null
    },
    {
      "nomeCampo": "descricao",
      "titulo": "Serviço",
      "subtitulo": "Descrição do serviço",
      "valorPadrao": null,
      "editavel": true,
      "obrigatorio": true,
      "visivel": true,
      "tipoDado": "texto",
      "ordem": 1,
      "isChavePrimaria": false,
      "isChaveEstrangeira": false,
      "nomeColuna": "descricao",
      "include": null,
      "views": [
        "viewInsert",
        "viewUpdate",
        "viewVisualizacao",
        "viewListagem"
      ],
      "expandOdata": false,
      "selectOdata": false,
      "noFilter": false,
      "conditionSql": false,
      "conditionSqlIfTrue": null,
      "conditionSqlIfFalse": null,
      "filtro": null,
      "componente": {
        "tamanhoMaximo": 60,
        "tamanhoMinimo": 0,
        "formato": "texto",
        "tipo": "textEdit",
        "typeId": "Framework.DataValidations.TextEditAttribute, FrameWork, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
      },
      "dicionario": null,
      "enumList": null
    },
    {
      "nomeCampo": "valor",
      "titulo": "Valor",
      "subtitulo": "Valor cobrado pelo serviço",
      "valorPadrao": null,
      "editavel": true,
      "obrigatorio": true,
      "visivel": true,
      "tipoDado": null,
      "ordem": 2,
      "isChavePrimaria": false,
      "isChaveEstrangeira": false,
      "nomeColuna": "valor",
      "include": null,
      "views": [
        "viewInsert",
        "viewUpdate",
        "viewVisualizacao",
        "viewListagem"
      ],
      "expandOdata": false,
      "selectOdata": false,
      "noFilter": false,
      "conditionSql": false,
      "conditionSqlIfTrue": null,
      "conditionSqlIfFalse": null,
      "filtro": null,
      "componente": {
        "tipo": "moedaEdit",
        "casasDecimais": 2,
        "ocultarSeparadorCasas": false,
        "valorMinimo": 0,
        "valorMaximo": 0
      },
      "dicionario": null,
      "enumList": null
    },
    {
      "nomeCampo": "desativado",
      "titulo": "Desativado",
      "subtitulo": "Desativado, quando desativado não pode ser utilizado para movimentações",
      "valorPadrao": null,
      "editavel": true,
      "obrigatorio": true,
      "visivel": true,
      "tipoDado": null,
      "ordem": 0,
      "isChavePrimaria": false,
      "isChaveEstrangeira": false,
      "nomeColuna": "desativado",
      "include": null,
      "views": [
        "viewInsert",
        "viewUpdate",
        "viewVisualizacao",
        "viewListagem"
      ],
      "expandOdata": false,
      "selectOdata": true,
      "noFilter": false,
      "conditionSql": false,
      "conditionSqlIfTrue": null,
      "conditionSqlIfFalse": null,
      "filtro": null,
      "componente": {
        "tipo": "checkBox"
      },
      "dicionario": null,
      "enumList": null
    },
    {
      "nomeCampo": "logCriacao",
      "titulo": "Criação",
      "subtitulo": "Data de criação do registro",
      "valorPadrao": null,
      "editavel": true,
      "obrigatorio": false,
      "visivel": true,
      "tipoDado": "data",
      "ordem": 3,
      "isChavePrimaria": false,
      "isChaveEstrangeira": false,
      "nomeColuna": "log_criacao",
      "include": null,
      "views": [
        "viewListagem",
        "viewFiltro",
        "viewInsert",
        "viewUpdate",
        "viewVisualizacao"
      ],
      "expandOdata": false,
      "selectOdata": true,
      "noFilter": false,
      "conditionSql": false,
      "conditionSqlIfTrue": null,
      "conditionSqlIfFalse": null,
      "filtro": null,
      "componente": {
        "tipo": "dateEdit",
        "typeId": "Framework.DataValidations.DataEditAttribute, FrameWork, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
      },
      "dicionario": null,
      "enumList": null
    },
    {
      "nomeCampo": "logAtualizacao",
      "titulo": "Últ. Atualização",
      "subtitulo": "Data e hora da última atualização sofrida pelo registro",
      "valorPadrao": null,
      "editavel": true,
      "obrigatorio": false,
      "visivel": true,
      "tipoDado": "datahora",
      "ordem": 5,
      "isChavePrimaria": false,
      "isChaveEstrangeira": false,
      "nomeColuna": "log_atualizacao",
      "include": null,
      "views": [
        "viewListagem",
        "viewFiltro",
        "viewInsert",
        "viewUpdate",
        "viewVisualizacao"
      ],
      "expandOdata": false,
      "selectOdata": true,
      "noFilter": false,
      "conditionSql": false,
      "conditionSqlIfTrue": null,
      "conditionSqlIfFalse": null,
      "filtro": null,
      "componente": {
        "tipo": "dateEdit",
        "typeId": "Framework.DataValidations.DataEditAttribute, FrameWork, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
      },
      "dicionario": null,
      "enumList": null
    },
    {
      "nomeCampo": "logPctUsuarioId",
      "titulo": "Últ. Usuário",
      "subtitulo": "Último usuário a alterar o registro",
      "valorPadrao": null,
      "editavel": true,
      "obrigatorio": false,
      "visivel": true,
      "tipoDado": "inteiro",
      "ordem": 6,
      "isChavePrimaria": false,
      "isChaveEstrangeira": false,
      "nomeColuna": "logPctUsuarioId",
      "include": null,
      "views": [
        "viewListagem",
        "viewFiltro",
        "viewInsert",
        "viewUpdate",
        "viewVisualizacao"
      ],
      "expandOdata": false,
      "selectOdata": true,
      "noFilter": false,
      "conditionSql": false,
      "conditionSqlIfTrue": null,
      "conditionSqlIfFalse": null,
      "filtro": null,
      "componente": {
        "tipo": "spinEdit",
        "typeId": "Framework.DataValidations.SpinEditAttribute, FrameWork, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
      },
      "dicionario": null,
      "enumList": null
    }
  ]
];